In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'0.12.1'

#### How TensorFlow Works
* Import/Generate Data
* Tranform & normalize data
  tf.nn.batch_norm_with_global_normalization(...)
* Partitionaing datasets into train,test & validation sets
* Setting hyperparameters
* Init variables & placeholders
  a_var = tf.constant(42)
  x_input = tf.placeholder(tf.float32,[])
* Define model structure
  tf.add(tf.mul(x_input, weight_matrix),b_matrix)
* Declare the loss function
  loss = tf.reduce_mean(tf.square(y_actual - y_pred))
* Initialize & train the model
  with tf.session(graph=graph) as session:
     ...
     session.run(...)
     ...
* Evaluate the model
* Tune hyperparameters
* Predict new outcomes


### Declaring Tensors

In [11]:
#Fixed tensors
zero_tsr = tf.zeros([4,5]) #filled with 0
ones_tsr = tf.ones([5,6]) # filled with 1
fill_tsr = tf.fill([5,6],33) # filled with 33
constant_tsr = tf.constant([1,2,3])

In [27]:
#Sequence tensors
linear_tsr = tf.linspace(1.0, 5.0, 20) 
#generates 20 numbrs between 1.0 & 5.0, needs start stop in float

int_seq_tsr = tf.range(5,20,2) 
# genartes 5,7,9 ...19

tf.random_uniform([3,5],minval=0, maxval=1)
#generates random number between 0 & 1 for 3 X 5 matrix

#shuffled_output = tf.random_shuffle(input_tensor)
#this shuffles the input tenor data

#cropped_out = tf.random_crop(input_tensor,10)
#crops a part of tensor data

#cropped_image = tf.random_crop(my_img, [100,100,3])

<tf.Tensor 'random_uniform_5:0' shape=(3, 5) dtype=float32>

In [31]:
#Create variables
v = tf.Variable(tf.zeros([4,5]))

### Using Placeholders and Variables
* The main way to create variable is by using Variable() function which takes a tensor as an input & outputs a variable

In [32]:
my_var = tf.Variable(tf.zeros([2,3]))

In [35]:
sess = tf.Session()
init_ops = tf.global_variables_initializer()
sess.run(init_ops)

In [36]:
init_ops

In [37]:
my_var

In [39]:
sess = tf.Session()
x = tf.placeholder(tf.float32, shape=[2,2])
y = tf.identity(x)
import numpy as np
x_vals = np.random.rand(2,2) # matrix of 2x2 random numbers
sess.run(y,feed_dict={x:x_vals})

array([[ 0.18858217,  0.1615514 ],
       [ 0.34884241,  0.04597388]], dtype=float32)

In [49]:
sess = tf.Session()
first_var = tf.Variable(tf.zeros([2,3]))
sess.run(first_var.initializer)
second_var = tf.Variable(tf.zeros_like(first_var))
sess.run(second_var.initializer)

In [52]:
sess = tf.Session()
x = tf.Variable(tf.ones([2,2]))
y = tf.identity(x)
import numpy as np
x_vals = np.random.rand(2,2) # matrix of 2x2 random numbers
sess.run(x.initializer) # init the variable
sess.run(y) # execute the pipeline

array([[ 1.,  1.],
       [ 1.,  1.]], dtype=float32)

### Working with Matrices
* Create Matrix
* Addition & Substraction
* Many more operations

In [58]:
identity_matrix = tf.diag([1.0,1.0,1.0])
A = tf.truncated_normal([2,3])
B = tf.fill([2,3],5.0)
C = tf.random_uniform([3,2])
D = tf.convert_to_tensor(np.array([ [1., 2., 3.], [-3., -7., -1.], [0, 5., -2.]]))

In [60]:
print(sess.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [65]:
print(type(sess.run(A)))

<class 'numpy.ndarray'>


In [63]:
print(type(sess.run(D)))

<class 'numpy.ndarray'>


In [64]:
type(D)

tensorflow.python.framework.ops.Tensor

In [66]:
print (D)

Tensor("Const_2:0", shape=(3, 3), dtype=float64)


In [67]:
sess.run(A+B)

array([[ 5.46294832,  5.34233046,  5.12082815],
       [ 4.91442442,  5.23717976,  5.16378117]], dtype=float32)

In [68]:
A+B

<tf.Tensor 'add_1:0' shape=(2, 3) dtype=float32>

In [69]:
print(sess.run(A+B))

[[ 3.93572426  4.68090439  4.00359535]
 [ 5.86310816  3.98890042  5.20362043]]


In [70]:
sess.run(tf.matmul(B, identity_matrix))

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.]], dtype=float32)

In [71]:
sess.run(tf.transpose(C))

array([[ 0.61821449,  0.16552651,  0.4834522 ],
       [ 0.34877789,  0.12576318,  0.36334288]], dtype=float32)

In [72]:
sess.run(tf.matrix_inverse(D))

array([[-0.5       , -0.5       , -0.5       ],
       [ 0.15789474,  0.05263158,  0.21052632],
       [ 0.39473684,  0.13157895,  0.02631579]])

In [73]:
sess.run(tf.cholesky(identity_matrix))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]], dtype=float32)

### Declaring Operations

In [75]:
import tensorflow as tf
sess = tf.Session()

In [77]:
sess.run(tf.div(3.,4))

0.75

In [78]:
sess.run(tf.mod(22.0,5.0))

2.0

In [81]:
sess.run(tf.cross([1., 0., 0], [0., 1., 0.]))

array([ 0.,  0.,  1.], dtype=float32)

### Implementing Activation Functions
* Activation functions live in the neural network library in TensorFlow

In [82]:
sess.run(tf.nn.relu([-3., 3., 10]))

array([  0.,   3.,  10.], dtype=float32)

In [83]:
sess.run(tf.nn.relu6([-3., 3., 10]))

array([ 0.,  3.,  6.], dtype=float32)

In [84]:
sess.run(tf.nn.sigmoid([-1., 0., 1.]))

array([ 0.26894143,  0.5       ,  0.7310586 ], dtype=float32)

In [86]:
sess.run(tf.nn.tanh([-1., 0., 1.]))

array([-0.76159418,  0.        ,  0.76159418], dtype=float32)

In [88]:
sess.run(tf.nn.softsign([-1., 0., -1.]))
#x /abs(x)+1

array([-0.5,  0. , -0.5], dtype=float32)