## Agenda
* How TensorFlow Works
* Declaring Variables and Tensors
* Using Placeholders and Variables
* Working with Matrices
* Declaring Operations
* Implementing Activation Functions

### How TensorFlow Works

#### Declaring Tensors
* Basic Unit of TensorFlow

In [1]:
import tensorflow as tf

### Fixed Tensors

In [2]:
zero_tsr = tf.zeros([4,5])

In [3]:
zero_tsr

<tf.Tensor 'zeros:0' shape=(4, 5) dtype=float32>

In [4]:
ones_tsr = tf.ones([6,7])

In [5]:
ones_tsr

<tf.Tensor 'ones:0' shape=(6, 7) dtype=float32>

In [7]:
filled_tsr = tf.fill([3,4],99)

In [8]:
constant_tsr = tf.constant([1,2,3])

In [9]:
# Tensors of similar shape
zero_similar = tf.zeros_like(constant_tsr)
zero_similar

<tf.Tensor 'zeros_like:0' shape=(3,) dtype=int32>

### Sequence tensors

In [13]:

linear_tsr = tf.linspace(start=0.0, stop=1.0, num=3)

In [14]:
linear_tsr

<tf.Tensor 'LinSpace_2:0' shape=(3,) dtype=float32>

In [15]:
int_seq_rng = tf.range(start=6, limit=15, delta=3)

In [16]:
int_seq_rng

<tf.Tensor 'range:0' shape=(3,) dtype=int32>

### Random Tensors

In [17]:
rand_tsr = tf.random_uniform([3,4],minval=0,maxval=1)

In [18]:
rand_tsr

<tf.Tensor 'random_uniform:0' shape=(3, 4) dtype=float32>

In [19]:
tf.random_shuffle(rand_tsr)

<tf.Tensor 'RandomShuffle:0' shape=(3, 4) dtype=float32>

In [22]:
tf.random_crop(rand_tsr,[2,2])

<tf.Tensor 'random_crop_2:0' shape=(2, 2) dtype=float32>

## Using Placeholders & Variables 

In [24]:
my_var = tf.Variable(tf.zeros([2,3]))
#Variable function takes tensor as an input & outputs a variable

In [25]:
my_var

In [26]:
sess = tf.Session()

In [28]:
sess.run(ones_tsr)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]], dtype=float32)

In [33]:
a = sess.run(my_var.initializer)

In [36]:
tfops = tf.global_variables_initializer()

In [37]:
sess.run(tfops)

In [39]:
sess = tf.Session()

In [40]:
x = tf.placeholder(tf.float32, shape=[2,2])

In [41]:
y = tf.identity(x)

In [43]:
import numpy as np
x_vals = np.random.rand(2,2)

In [44]:
sess = tf.Session()

In [45]:
sess.run(y, feed_dict={x:x_vals})

array([[ 0.30312061,  0.05721265],
       [ 0.355694  ,  0.56984359]], dtype=float32)

In [46]:
x_vals

array([[ 0.30312063,  0.05721265],
       [ 0.355694  ,  0.56984357]])

In [47]:
x_vals

array([[ 0.30312063,  0.05721265],
       [ 0.355694  ,  0.56984357]])

In [48]:
### Variable
sess = tf.Session()
first_var = tf.Variable(tf.zeros([2,3]))

In [49]:
sess.run(first_var.initializer)

In [50]:
second_var  = tf.Variable(tf.zeros_like(first_var))

In [51]:
sess.run(second_var.initializer)

In [52]:
tf.__version__

'0.12.1'