In [1]:
import tensorflow as tf

In [2]:
# tf.constant() - creats a "constant" op. It takes a single value & output same value to nodes directly connected.
a = tf.constant(5, name="input_a")
b = tf.constant(3, name="input_b")

In [3]:
a
#no values since graph is not run as of now

<tf.Tensor 'input_a:0' shape=() dtype=int32>

In [4]:
c = tf.multiply(a,b, name="mul_c")
d = tf.add(a,b, name="add_d")
e = tf.add(c,d, name="add_e")

In [5]:
sess = tf.Session()

In [6]:
sess.run(e)

23

In [ ]:
##Now, instead of scalar values, we will try vector

In [11]:
a = tf.constant([5,3], name="input_a") #vector creation

In [12]:
b = tf.reduce_prod(a, name="prob_b")

In [13]:
c = tf.reduce_sum(a, name="sum_c")

In [14]:
d = tf.add(b,c,name="add_d")

In [15]:
sess = tf.Session()

In [16]:
sess.run(d)

23

In [23]:
#Feeding numpy to tensorflow
import numpy as np

In [18]:
np_a = np.array([3,4])
np_b = np.array([5,6])

In [20]:
np_e = tf.add(np_a,np_b,name="my_add")

In [21]:
sess = tf.Session()

In [22]:
sess.run(np_e)

array([ 8, 10])

In [25]:
#Having multiple sessions
g = tf.Graph()

In [32]:
#Create new graphs
g1 = tf.Graph()
g2 = tf.Graph()

In [36]:
with g1.as_default():
    a = tf.constant(15, name="input_a")
    b = tf.constant(13, name="input_b")
    c = tf.add(a,b)

In [37]:
sess=tf.Session(graph=g1)

In [45]:
e = sess.run(c)

In [40]:
with g2.as_default():
    a = tf.constant(25, name="input_a")
    b = tf.constant(23, name="input_b")
    c = tf.add(a,b)

In [41]:
sess=tf.Session(graph=g2)

In [44]:
b = sess.run(c)

In [43]:
sess.run([a,b])

[25, 23]

In [46]:
#Creating Variables
my_var = tf.Variable(3,name="my_var")

In [47]:
add = tf.add(5,my_var)

In [48]:
mul = tf.multiply(6,my_var)

In [50]:
e = tf.add(add,mul)

In [51]:
zeros = tf.zeros([2,2])

In [53]:
ones = tf.ones([3,3])

In [54]:
sess = tf.Session()

In [55]:
sess.run(ones)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [56]:
uniform = tf.random_uniform([3,3,3],minval=0,maxval=10)

In [57]:
sess.run(uniform)

array([[[ 0.48645973,  1.2263155 ,  9.40589046],
        [ 2.02124119,  6.05091667,  8.7031641 ],
        [ 1.49981022,  3.16378117,  1.11089468]],

       [[ 8.18737507,  9.23777199,  3.47019076],
        [ 0.17691255,  6.43301487,  7.45279551],
        [ 0.73895693,  8.25851822,  8.53838062]],

       [[ 2.9097271 ,  3.14760089,  2.19149828],
        [ 2.43833303,  2.14926243,  3.38890314],
        [ 9.59069824,  7.09852934,  5.64373732]]], dtype=float32)

In [58]:
normal = tf.random_normal([2,2],mean=5.0, stddev=1.0)

In [59]:
sess.run(normal)

array([[ 4.34244823,  3.13942409],
       [ 5.02525711,  3.77553844]], dtype=float32)

In [60]:
## Variable Initilization

In [62]:
init = tf.global_variables_initializer()

In [63]:
sess.run(init)

In [64]:
a

<tf.Tensor 'input_a:0' shape=() dtype=int32>

In [69]:
var1 = tf.Variable(0, name="initialize_me")
var2 = tf.Variable(1, name="no_initialization")
init = tf.variables_initializer([var1], name="init_var1")
sess = tf.Session()
sess.run(init)

In [70]:
# Create variable with starting value of 1
my_var = tf.Variable(1)

In [71]:
# Create an operation that multiplies the variable by 2 each time it is run
#to change value of variable, use .assign function
my_var_times_two = my_var.assign(my_var * 2)

In [73]:
# Initialization operation
init = tf.global_variables_initializer()

In [74]:
# Start a session
sess = tf.Session()

In [75]:
# Initialize variable
sess.run(init)

In [76]:
sess.run(my_var_times_two)

2

In [77]:
sess.run(my_var_times_two)

4

In [78]:
sess.run(my_var_times_two)

8

In [79]:
# Increment by 1
sess.run(my_var.assign_add(1))


9

In [80]:
l = [1,2,3,4]
m = [5,6,7,8]

In [81]:
k = [1,5,2,6,3,7,4,8]

In [86]:
k = []
for i,j in zip(l,m):
    k.append(i)
    k.append(j)
   

In [87]:
print (k)

[1, 5, 2, 6, 3, 7, 4, 8]


In [89]:
list(zip(l,m))

[(1, 5), (2, 6), (3, 7), (4, 8)]