In [5]:
import pandas as pd

In [6]:
income_data = pd.read_csv('data/income.csv',header=None)

In [7]:
income_data.columns = ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','income']

In [8]:
income_data.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [9]:
income_data.workclass.unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay', ' Never-worked'], dtype=object)

In [10]:
income_data.education.unique()

array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
       ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',
       ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',
       ' Preschool', ' 12th'], dtype=object)

In [11]:
income_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    32561 non-null object
income            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [12]:
income_data.occupation.unique()

array([' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',
       ' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair',
       ' Transport-moving', ' Farming-fishing', ' Machine-op-inspct',
       ' Tech-support', ' ?', ' Protective-serv', ' Armed-Forces',
       ' Priv-house-serv'], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder
for col in ['workclass','native-country','sex','income','race','relationship','occupation','marital-status','education','workclass']:
    le = LabelEncoder()
    income_data[col] = le.fit_transform(income_data[col])

In [14]:
income_data.head()

age  workclass  fnlwgt  education  education-num  marital-status  \
0   39          7   77516          9             13               4   
1   50          6   83311          9             13               2   
2   38          4  215646         11              9               0   
3   53          4  234721          1              7               2   
4   28          4  338409          9             13               2   

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0           1             1     4    1          2174             0   
1           4             0     4    1             0             0   
2           6             1     4    1             0             0   
3           6             0     2    1             0             0   
4          10             5     2    0             0             0   

   hours-per-week  native-country  income  
0              40              39       0  
1              13              39       0  
2              40              39       0  
3              40              39       0  
4              40               5       0

In [15]:
trainX = income_data[['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country']]

In [17]:
trainX.as_matrix().shape

(32561, 14)

In [18]:
trainy = income_data.income

In [26]:
trainy

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        1
8        1
9        1
10       1
11       1
12       0
13       0
14       1
15       0
16       0
17       0
18       0
19       1
20       1
21       0
22       0
23       0
24       0
25       1
26       0
27       1
28       0
29       0
        ..
32531    0
32532    1
32533    1
32534    0
32535    0
32536    1
32537    0
32538    1
32539    1
32540    0
32541    0
32542    0
32543    0
32544    0
32545    1
32546    0
32547    0
32548    0
32549    0
32550    0
32551    0
32552    0
32553    0
32554    1
32555    0
32556    0
32557    1
32558    0
32559    0
32560    1
Name: income, Length: 32561, dtype: int64

In [19]:
import tensorflow as tf
import tflearn

In [20]:
def dnn_model(num_layers,layer_info):
    tf.reset_default_graph()
    
    net = tflearn.input_data(shape=[None,14])
    
    for idx,layer in enumerate(range(1,num_layers+1)):
        net = tflearn.fully_connected(net,layer_info[idx],activation='ReLU')
    
    net = tflearn.fully_connected(net,2, activation='softmax')
    net = tflearn.regression(net, optimizer='sgd', learning_rate=0.01, loss='categorical_crossentropy')
    
    model = tflearn.DNN(net)
    return model

In [21]:
model = dnn_model(2,[64,32])

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [23]:
ohe = OneHotEncoder()
Y = ohe.fit_transform(trainy.values.reshape(-1,1))

In [25]:
Y.toarray()

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       ..., 
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.]])

In [34]:
model.fit(trainX.as_matrix(), Y.toarray(),validation_set=0.01,show_metric=True, batch_size=100, n_epoch=100)

Training Step: 32300  | total loss: 0.54375 | time: 0.783s
| SGD | epoch: 101 | loss: 0.54375 - acc: 0.7665 -- iter: 32200/32235
Training Step: 32301  | total loss: 0.55016 | time: 1.796s
| SGD | epoch: 101 | loss: 0.55016 - acc: 0.7609 | val_loss: 0.53288 - val_acc: 0.7761 -- iter: 32235/32235
--


In [36]:
model = dnn_model(1,[32])

In [37]:
model.fit(trainX.as_matrix(), Y.toarray(),validation_set=0.01,show_metric=True, batch_size=100, n_epoch=100)

Training Step: 32299  | total loss: 17.67183 | time: 0.727s
| SGD | epoch: 100 | loss: 17.67183 - acc: 0.2325 -- iter: 32200/32235
Training Step: 32300  | total loss: 17.65462 | time: 1.736s
| SGD | epoch: 100 | loss: 17.65462 - acc: 0.2333 | val_loss: 17.65786 - val_acc: 0.2331 -- iter: 32235/32235
--


In [38]:
layers = [1,2,3,3]
units = [[32],[32,32],[32,32,32],[128,64,32]]

In [80]:
def run_all():
    for idx,layer in enumerate(layers):
        model = dnn_model(layer,units[idx])
        model.fit(trainX.as_matrix(), Y.toarray(),validation_set=0.01,show_metric=True, batch_size=100, n_epoch=30)
        y_pred = model.predict(trainX.as_matrix())
        print (accuracy_score( Y.toarray(), y_pred.astype(int)))

In [52]:
model.predict_label([[39,7,77516,9,13,4,1,1,4,1,2170,0,40,39]])

array([[1, 0]])

In [53]:
ohe.transform([[0]]).toarray()

array([[ 1.,  0.]])

In [54]:
y_pred = model.predict(trainX.as_matrix())

In [78]:
y_pred.astype(int)

array([[0, 1],
       [0, 1],
       [0, 1],
       ..., 
       [0, 1],
       [0, 1],
       [0, 1]])

In [77]:
Y.toarray()

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       ..., 
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.]])

In [57]:
from sklearn.metrics import accuracy_score

In [60]:
import numpy as np
accuracy_score(np.array([[0, 1], [1, 1]]), np.ones((2, 2)))

0.5

In [79]:
accuracy_score( Y.toarray(), y_pred.astype(int))

0.24080955744602439

In [75]:
y_pred.shape

(32561, 2)

In [81]:
run_all()

Training Step: 9689  | total loss: 0.52348 | time: 0.933s
| SGD | epoch: 030 | loss: 0.52348 - acc: 0.7776 -- iter: 32200/32235
Training Step: 9690  | total loss: 0.52349 | time: 1.943s
| SGD | epoch: 030 | loss: 0.52349 - acc: 0.7789 | val_loss: 0.49280 - val_acc: 0.8006 -- iter: 32235/32235
--
0.00488314240963
