In [5]:
import tensorflow as tf

In [11]:
# Create some variables.
tf.reset_default_graph()
v1 = tf.get_variable("v1", shape=[3])
v2 = tf.get_variable("v2", shape=[5])

In [12]:
saver = tf.train.Saver({"v2":v2})

In [13]:
with tf.Session() as sess:
    saver.restore(sess,"D:/model.ckpt")
    print ("Model restored")
    #print (v1.eval())
    print (v2.eval())

INFO:tensorflow:Restoring parameters from D:/model.ckpt
Model restored
[-1. -1. -1. -1. -1.]


In [14]:
inc_dataset = tf.contrib.data.Dataset.range(100)

In [15]:
dec_dataset = tf.contrib.data.Dataset.range(0, -100, -1)

In [16]:
dataset = tf.contrib.data.Dataset.zip((inc_dataset, dec_dataset))

In [17]:
batched_dataset = dataset.batch(4)

In [18]:
iterator = batched_dataset.make_one_shot_iterator()

In [19]:
next_element = iterator.get_next()

In [22]:
with tf.Session() as sess:
    print(sess.run(next_element))
    print(sess.run(next_element))
    print(sess.run(next_element))

(array([0, 1, 2, 3], dtype=int64), array([ 0, -1, -2, -3], dtype=int64))
(array([4, 5, 6, 7], dtype=int64), array([-4, -5, -6, -7], dtype=int64))
(array([ 8,  9, 10, 11], dtype=int64), array([ -8,  -9, -10, -11], dtype=int64))


In [23]:
### Batching tensors with padding

In [30]:
tf.reset_default_graph()
dataset = tf.contrib.data.Dataset.range(100)

In [31]:
dataset = dataset.map(lambda x : tf.fill([tf.cast(x, tf.int32)],x))

In [32]:
dataset = dataset.padded_batch(4, padded_shapes=[None])
iterator = dataset.make_one_shot_iterator()

In [27]:
next_element = iterator.get_next()
with tf.Session() as sess:
    print(sess.run(next_element))
    print(sess.run(next_element))

[[0 0 0]
 [1 0 0]
 [2 2 0]
 [3 3 3]]
[[4 4 4 4 0 0 0]
 [5 5 5 5 5 0 0]
 [6 6 6 6 6 6 0]
 [7 7 7 7 7 7 7]]
