In [1]:
import tensorflow as tf

### Fixed Tensors

In [28]:
zers_tsr = tf.zeros([4,5])

In [29]:
with tf.Session() as sess:
    print (sess.run(zers_tsr))
    zers_tsr = zers_tsr + 2
    print (sess.run(zers_tsr))

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


In [30]:
type(zers_tsr)

tensorflow.python.framework.ops.Tensor

In [6]:
ones_tsr = tf.ones([3,4])

In [7]:
with tf.Session() as sess:
    print (sess.run(ones_tsr))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [8]:
fill_tsr = tf.fill([3,4],88)

In [9]:
with tf.Session() as sess:
    print (sess.run(fill_tsr))

[[88 88 88 88]
 [88 88 88 88]
 [88 88 88 88]]


### Sequence Tensors

In [10]:
lindata = tf.linspace(start=0.0, stop=1.0 , num=5)

In [11]:
with tf.Session() as sess:
    print (sess.run(lindata))

[ 0.    0.25  0.5   0.75  1.  ]


In [12]:
rand_data = tf.random_normal([4,4])

In [13]:
with tf.Session() as sess:
    print (sess.run(rand_data))

[[-0.5651834  -0.75627339 -1.07505512 -1.33949006]
 [-0.18402901 -0.73097408  0.49229071 -0.01601863]
 [-0.09801407  0.1732095  -1.36382282  0.82960379]
 [-0.26175088 -0.08604725 -1.15995622  1.48070812]]


In [14]:
d = tf.random_shuffle(rand_data)

In [16]:
with tf.Session() as sess:
    print (sess.run(d))

[[-0.84147167  0.9702239  -0.52596253  0.19821416]
 [-0.64050829  0.91119027 -0.85487616  1.27221894]
 [-0.93836033 -1.32602131 -0.5849613  -0.30340749]
 [ 0.00843196  1.22454345 -0.87759376 -1.57049656]]


In [17]:
help(tf.random_normal)

Help on function random_normal in module tensorflow.python.ops.random_ops:

random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
    Outputs random values from a normal distribution.
    
    Args:
      shape: A 1-D integer Tensor or Python array. The shape of the output tensor.
      mean: A 0-D Tensor or Python value of type `dtype`. The mean of the normal
        distribution.
      stddev: A 0-D Tensor or Python value of type `dtype`. The standard deviation
        of the normal distribution.
      dtype: The type of the output.
      seed: A Python integer. Used to create a random seed for the distribution.
        See
        @{tf.set_random_seed}
        for behavior.
      name: A name for the operation (optional).
    
    Returns:
      A tensor of the specified shape filled with random normal values.



### Placeholders & Variables

In [25]:
my_var = tf.Variable(tf.zeros([2,3]))

In [27]:
with tf.Session() as sess:
    sess.run(my_var.initializer)
    print (sess.run(my_var))
    my_var = tf.add(my_var,5)
    print (sess.run(my_var))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 5.  5.  5.]
 [ 5.  5.  5.]]


In [31]:
type(my_var)

tensorflow.python.framework.ops.Tensor

In [32]:
t = tf.constant([1,2,3])

In [35]:
with tf.Session() as sess:
    t = t + 2
    print (sess.run(t))

[3 4 5]


In [36]:
with tf.Session() as sess:
    print (sess.run(t))

[3 4 5]


In [37]:
x = tf.placeholder(tf.float32, shape=[2,2])

In [39]:
with tf.Session() as sess:
    print (sess.run(x, feed_dict={x:[[3,3],[4,4]]}))

[[ 3.  3.]
 [ 4.  4.]]


In [40]:
tf.get_default_graph()

In [41]:
g = tf.Graph()

In [42]:
g

In [43]:
a = tf.constant(5)

In [44]:
a.graph

In [45]:
with g.as_default():
    b = tf.constant(7)

In [46]:
b.graph

In [47]:
a = tf.get_default_graph()

In [61]:
a = tf.constant(5)
b = tf.placeholder(tf.int32,shape=[2,2])
c = tf.constant(15)
d = tf.constant(26)
e = tf.constant(25)
f = b + a

In [62]:
with tf.Session() as sess:
    fetches = [a,b,c,d,e,f]
    outs = sess.run(fetches,feed_dict={b:[[4,4],[5,5]]})

In [63]:
outs

[5, array([[4, 4],
        [5, 5]]), 15, 26, 25, array([[ 9,  9],
        [10, 10]])]

In [64]:
a.graph

In [66]:
tf.get_default_graph()